### ISSUE TITLE
“other functions can also defined by the user as described below”，but I can not find it

### ISSUE THREAD

**Issue by A-Pai** [m-Py/anticlust#61]
https://search.r-project.org/CRAN/refmans/anticlust/html/anticlustering.html

![image](https://github.com/user-attachments/assets/7c317d9d-8728-4648-830c-24b59a4e09e2)

“other functions can also defined by the user as described below”，but I can not find it

**Comment by m-Py** [comment]
It is documented under "Optimize a custom objective function".  If any questions remain, please tell me, I know this section is not very detailed. (I think most people don't use this functionality). 

Will close this issue, but feel free to post any follow-up questions here.
